services:
  - type: web
    name: monprojetgl
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: "gunicorn monprojet.wsgi:application"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: assistant
          property: connectionString

databases:
  - name: assistant
    databaseName: dbname
    user: dbuser
